# Delete operations

In [1]:
pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 2.0 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [3]:
import pymysql

In [4]:
con=pymysql.connect(host='mysql-python-ethan-python.c.aivencloud.com',port=26428,user='avnadmin',password='AVNS_tcr4f3ZnICCfhmNruwF',database='sharayudb')
curs=con.cursor()

In [8]:
no=int(input('Enter account number : '))
curs.execute('select * from accounts where accno=%d' %no)
data=curs.fetchone()
if data:
  print(data)
  cho=input('do you really want to delete(yes/no) : ')
  if cho=='yes':
    cnt=curs.execute("delete from accounts where accno=%d" %no)
    con.commit()
    print('account deleted successfully')
  else:
    print('delete cancelled...')
else:
  print('account number not found')

Enter account number : 1035
(1035, 'harry kane', 'current', 78751.0)
do you really want to delete(yes/no) : yes
account deleted successfully

In [9]:
con.close()