**Import data from Excel sheet to Pandas DF**

In [1]:
import pandas

In [2]:
file=pandas.ExcelFile("countrydetails.xlsx")

In [3]:
df=file.parse("Sheet1")

In [4]:
print(df)

         Country           Capital        Currency  \
0    Afghanistan             Kabul         Afghani
1        Albania            Tirane             Lek
2        Algeria           Algiers  Algerian Dinar
3        Andorra  Andorra la Vella            Euro
4         Angola            Luanda          Kwanza
..           ...               ...             ...
141        Qatar              Doha    Qatari Riyal
142      Romania         Bucharest  Romanian Rupee
143      Romania         Bucharest  Romanian Rupee
144       Russia            Moscow           Ruble
145       Rwanda            Kigali   Rwandan Franc

              Primary Language(s)
0            Dari Persian; Pashto
1                        Albanian
2       Arabic; Tamazight; French
3                         Catalan
4                      Portuguese
..                            ...
141                        Arabic
142                      Romanian
143                      Romanian
144                       Russian
145  Kinyarwanda; French; English

[146 rows x 4 columns]

In [7]:
file=pandas.ExcelFile("population.xlsx")
df=file.parse("Sheet2")
print(df)

                                Country    Region           Subregion  \
0                              China[a]      Asia        Eastern Asia
1                                 India      Asia       Southern Asia
2                         United States  Americas    Northern America
3                             Indonesia      Asia  South-eastern Asia
4                              Pakistan      Asia       Southern Asia
..                                  ...       ...                 ...
228         Montserrat (United Kingdom)  Americas           Caribbean
229   Falkland Islands (United Kingdom)  Americas       South America
230                                Niue   Oceania           Polynesia
231               Tokelau (New Zealand)   Oceania           Polynesia
232                     Vatican City[z]    Europe     Southern Europe

     Population2018  Population2019  Change
0        1427647786      1433783686  0.0043
1        1352642280      1366417754  0.0102
2         327096265       329064917  0.0060
3         267670543       270625568  0.0110
4         212228286       216565318  0.0204
..              ...             ...     ...
228            4993            4989 -0.0008
229            3234            3377  0.0442
230            1620            1615 -0.0031
231            1319            1340  0.0159
232             801             799 -0.0025

[233 rows x 6 columns]

**Export DF data to a CSV dataset**

In [8]:
df.to_csv("populationdata.csv")